from . import helpdesk_call
from . import helpdesk_ticket
from . import sale_order
from . import stock_picking
from . import project_task
from . import mail_thread
from . import inventory_tag
from . import product_template
from . import res_partner
from . import account_move
from . import hr_employee
from . import models
from . import cancelled_remission_reason
from . import cancelled_remission
from . import account_invoice_report
