from . import helpdesk_call
from . import helpdesk_ticket
from . import res_partner
from . import sale_order
from . import stock_picking
from . import project_task
from . import mail_thread
from . import inventory_tag
from . import product_template
from . import account_move
from . import account_move_line
from . import hr_employee
from . import models
from . import cancelled_remission_reason
from . import cancelled_remission
from . import account_invoice_report
from . import analytic_distribution_model
from . import purchase_order_line
from . import sale_order_line
from . import mail_followers
#from . import stock_move_line
from . import stock_move
from . import procurement_group
from . import helpdesk_attribution
from . import helpdesk_team
from . import helpdesk_ticket_type
