{
    'name': 'XE Lunch Kiosk',
    'version': '17.0.1.1.2',
    'summary': 'Meal Service Registration via Barcode',
    'author': 'XE Brands',
    'category': 'Human Resources',
    'depends': ['web', 'hr', 'barcodes'],
    'data': [
        'security/xe_lunch_kiosk_groups.xml',
        'security/ir.model.access.csv',
        'views/kiosk_views.xml',
        'views/kiosk_template.xml',
    ],
    'assets': {
        'xe_lunch_kiosk.assets_kiosk': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_frontend_helpers'),
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            ('include', 'web._assets_bootstrap_frontend'),
            ('include', 'web._assets_core'),
            'web/static/src/webclient/barcode/barcode_scanner.js',
            'web/static/src/webclient/barcode/barcode_scanner.xml',
            'web/static/src/webclient/barcode/barcode_scanner.scss',
            'web/static/src/webclient/barcode/crop_overlay.js',
            'web/static/src/webclient/barcode/crop_overlay.xml',
            'web/static/src/webclient/barcode/crop_overlay.scss',
            'web/static/src/webclient/barcode/ZXingBarcodeDetector.js',
            'barcodes/static/src/components/barcode_scanner.js',
            'barcodes/static/src/components/barcode_scanner.xml',
            'barcodes/static/src/components/barcode_scanner.scss',

            'xe_lunch_kiosk/static/src/css/kiosk.css',
            'xe_lunch_kiosk/static/src/js/kiosk_app.js',
            'xe_lunch_kiosk/static/src/xml/kiosk_app.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
