from . import test_meli_config_access
from . import test_meli_config_token
from . import test_meli_config_connect
from . import test_meli_config_retry
from . import test_meli_full_cancellation
from . import test_meli_invoice_document
from . import test_meli_invoice_import_batch
from . import test_controller
from . import test_cron
from . import test_meli_sku_mapping
from . import test_res_partner_meli
from . import test_sale_order_meli
from . import test_sale_order_search_meli
from . import test_meli_security_groups
